<SearchScreen>:
    MDFloatLayout:
        MDBoxLayout:
            md_bg_color: 0,0,0,1
            size_hint: 1,0.075
            pos_hint: {"top":1,"right":1}
            MDTextFieldRect:
                id:search_bar
                hint_text: "Search"
                icon:"file-search"
        MDBoxLayout:
            size_hint: 1,0.924
            pos_hint: {"top":0.924,"right":1}
            id:search_advices
